# TRACY RENZ FAURA ECE3A

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

df = pd.read_csv('C:/Users/faura/OneDrive/MATHEDA/Dataset New/transformer-voltage.csv',
                 index_col= 'Sample',
                 delimiter= ','
                 )

df

        Voltage
Sample
1         117.0
2         118.3
3         119.5
4         119.5
5         119.6
6         119.6
7         119.7
8         119.7
9         119.7
10        119.8
11        119.8
12        119.8
13        120.0
14        120.4
15        120.5
16        120.5
17        120.5
18        120.1
19        120.1
20        120.1
21        120.2
22        120.2
23        120.2
24        121.0
25        121.1
26        121.6
27        121.7
28        122.2
29        122.5
30        123.8

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 1 to 30
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Voltage  30 non-null     float64
dtypes: float64(1)
memory usage: 480.0 bytes

In [9]:
df.describe()

          Voltage
count   30.000000
mean   120.290000
std      1.243285
min    117.000000
25%    119.700000
50%    120.100000
75%    120.500000
max    123.800000

In [ ]:
alpha = 0.01
z_critical = stats.norm.ppf(1-alpha/2)
z_critical